
http://localhost:3000/produto

###

POST http://localhost:3000/produto HTTP/1.1
content-type: application/json

{
    "id": 4,
    "nome": "Doando sangue",
    "quantidade": 15,
    "descricao": "",
    "valorunitario": 29.9,
    "categoria": "Camisa",
    "tamanho": "G",
    "volume": "Não Possui",
    "material": "Algodão",
    "genero": "Feminino"
}

###

GET http://localhost:3000/produto